version: '3'
services:
  mongodb-server:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_PRIMARY_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
    command: mongod --smallfiles --bind_ip_all
    volumes:
      - /data/db
      - /data/configdb
    restart: always

  mongo-express:
    #container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      #ME_CONFIG_MONGODB_SERVER: mongodb-server is used to tell the mongo-express
      #service that the mongo service name(default mongo) is changed to mongodb-server.
      ME_CONFIG_MONGODB_SERVER: mongodb-server
      #ME_CONFIG_BASICAUTH_USERNAME: admin and ME_CONFIG_BASICAUTH_PASSWORD: admin is used to tell
      #mongo-express service to use the username admin and the password admin for authentication.
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
#volumes:
#  mongo-data: